export const candidates = [
    {
        firstname: 'John',
        lastname: 'Doe',
        role: 'candidate',
        phone: '555-1234',
        email: 'john.doe@example.com',
        companyID: 'COMP123',
        password: 'password123',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'Software Developer',
        experience: '5 years',
        githubLink: 'https://github.com/johndoe',
        resume: '/public/resumes/john-doe.pdf',
    },
    {
        firstname: 'Jane',
        lastname: 'Smith',
        role: 'candidate',
        phone: '555-5678',
        email: 'jane.smith@example.com',
        companyID: 'COMP456',
        password: 'password456',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'Product Manager',
        experience: '7 years',
        githubLink: 'https://github.com/janesmith',
        resume: '/public/resumes/jane-smith.pdf',
    },
    {
        firstname: 'Alice',
        lastname: 'Johnson',
        role: 'candidate',
        phone: '555-8765',
        email: 'alice.johnson@example.com',
        companyID: 'COMP789',
        password: 'password789',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'Data Scientist',
        experience: '4 years',
        githubLink: 'https://github.com/alicejohnson',
        resume: '/public/resumes/alice-johnson.pdf',
    },
    {
        firstname: 'Bob',
        lastname: 'Williams',
        role: 'candidate',
        phone: '555-4321',
        email: 'bob.williams@example.com',
        companyID: 'COMP101',
        password: 'password101',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'UX Designer',
        experience: '6 years',
        githubLink: 'https://github.com/bobwilliams',
        resume: '/public/resumes/bob-williams.pdf',
    },
    {
        firstname: 'Emma',
        lastname: 'Brown',
        role: 'candidate',
        phone: '555-1239',
        email: 'emma.brown@example.com',
        companyID: 'COMP202',
        password: 'password202',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'DevOps Engineer',
        experience: '3 years',
        githubLink: 'https://github.com/emmabrown',
        resume: '/public/resumes/emma-brown.pdf',
    },
    {
        firstname: 'Michael',
        lastname: 'Davis',
        role: 'candidate',
        phone: '555-1240',
        email: 'michael.davis@example.com',
        companyID: 'COMP303',
        password: 'password303',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'System Administrator',
        experience: '8 years',
        githubLink: 'https://github.com/michaeldavis',
        resume: '/public/resumes/michael-davis.pdf',
    },
    {
        firstname: 'Sophia',
        lastname: 'Miller',
        role: 'candidate',
        phone: '555-1241',
        email: 'sophia.miller@example.com',
        companyID: 'COMP404',
        password: 'password404',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'Marketing Specialist',
        experience: '2 years',
        githubLink: 'https://github.com/sophiamiller',
        resume: '/public/resumes/sophia-miller.pdf',
    },
    {
        firstname: 'James',
        lastname: 'Wilson',
        role: 'candidate',
        phone: '555-1242',
        email: 'james.wilson@example.com',
        companyID: 'COMP505',
        password: 'password505',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'Full-Stack Developer',
        experience: '6 years',
        githubLink: 'https://github.com/jameswilson',
        resume: '/public/resumes/james-wilson.pdf',
    },
    {
        firstname: 'Olivia',
        lastname: 'Martinez',
        role: 'candidate',
        phone: '555-1243',
        email: 'olivia.martinez@example.com',
        companyID: 'COMP606',
        password: 'password606',
        profilePic: '/public/images/dog.jpg',
        jobRole: 'Graphic Designer',
        experience: '5 years',
        githubLink: 'https://github.com/oliviamartinez',
        resume: '/public/resumes/olivia-martinez.pdf',
    },
    {
        firstname: 'Daniel',
        lastname: 'Anderson',
        role: 'candidate',
        phone: '555-1244',
        email: 'daniel.anderson@example.com',
        companyID: 'COMP707',
        password: 'password707',
        profilePic: '/public/images/dog.jpg',
    }
]