export const candidates = [
    {
        firstname: 'John',
        lastname: 'Doe',
        role: 'candidate',
        phone: '555-1234',
        email: 'john.doe@example.com',
        companyID: 'COMP123',
        password: 'password123',
        profilePic: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHByb2ZpbGV8ZW58MHx8fHwxNjE2Nzg3NjA0&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'Software Developer',
        experience: '5 years',
        githubLink: 'https://github.com/johndoe',
        resume: '/public/resumes/john-doe.pdf',
    },
    {
        firstname: 'Jane',
        lastname: 'Smith',
        role: 'candidate',
        phone: '555-5678',
        email: 'jane.smith@example.com',
        companyID: 'COMP456',
        password: 'password456',
        profilePic: 'https://images.unsplash.com/photo-1595152772823-1f5c9b645c1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDV8fHByb2ZpbGV8ZW58MHx8fHwxNjE2Nzg3NjA0&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'Product Manager',
        experience: '7 years',
        githubLink: 'https://github.com/janesmith',
        resume: '/public/resumes/jane-smith.pdf',
    },
    {
        firstname: 'Alice',
        lastname: 'Johnson',
        role: 'candidate',
        phone: '555-8765',
        email: 'alice.johnson@example.com',
        companyID: 'COMP789',
        password: 'password789',
        profilePic: 'https://images.unsplash.com/photo-1621604335172-2f38c4f50e95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDE4fHxwcm9maWxlfGVufDB8fHx8MTY4MTQ2NzM3MA&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'Data Scientist',
        experience: '4 years',
        githubLink: 'https://github.com/alicejohnson',
        resume: '/public/resumes/alice-johnson.pdf',
    },
    {
        firstname: 'Bob',
        lastname: 'Williams',
        role: 'candidate',
        phone: '555-4321',
        email: 'bob.williams@example.com',
        companyID: 'COMP101',
        password: 'password101',
        profilePic: 'https://images.unsplash.com/photo-1621604335139-872b31c63f6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDE1fHxwcm9maWxlfGVufDB8fHx8MTY4MTQ2NzM3MA&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'UX Designer',
        experience: '6 years',
        githubLink: 'https://github.com/bobwilliams',
        resume: '/public/resumes/bob-williams.pdf',
    },
    {
        firstname: 'Emma',
        lastname: 'Brown',
        role: 'candidate',
        phone: '555-1239',
        email: 'emma.brown@example.com',
        companyID: 'COMP202',
        password: 'password202',
        profilePic: 'https://images.unsplash.com/photo-1621604335196-8c7c8f7fd60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDI0fHxwcm9maWxlfGVufDB8fHx8MTY4MTQ2NzM3MA&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'DevOps Engineer',
        experience: '3 years',
        githubLink: 'https://github.com/emmabrown',
        resume: '/public/resumes/emma-brown.pdf',
    },
    {
        firstname: 'Michael',
        lastname: 'Davis',
        role: 'candidate',
        phone: '555-1240',
        email: 'michael.davis@example.com',
        companyID: 'COMP303',
        password: 'password303',
        profilePic: 'https://images.unsplash.com/photo-1621604335141-639c1dbd8a5a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDE3fHxwcm9maWxlfGVufDB8fHx8MTY4MTQ2NzM3MA&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'System Administrator',
        experience: '8 years',
        githubLink: 'https://github.com/michaeldavis',
        resume: '/public/resumes/michael-davis.pdf',
    },
    {
        firstname: 'Sophia',
        lastname: 'Miller',
        role: 'candidate',
        phone: '555-1241',
        email: 'sophia.miller@example.com',
        companyID: 'COMP404',
        password: 'password404',
        profilePic: 'https://images.unsplash.com/photo-1595152772834-219674b2a8a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDN8fHByb2ZpbGV8ZW58MHx8fHwxNjg1NzM4MjY1&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'Marketing Specialist',
        experience: '2 years',
        githubLink: 'https://github.com/sophiamiller',
        resume: '/public/resumes/sophia-miller.pdf',
    },
    {
        firstname: 'James',
        lastname: 'Wilson',
        role: 'candidate',
        phone: '555-1242',
        email: 'james.wilson@example.com',
        companyID: 'COMP505',
        password: 'password505',
        profilePic: 'https://images.unsplash.com/photo-1595152772836-219674b2a8a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDZ8fHByb2ZpbGV8ZW58MHx8fHwxNjg1NzM4MjY1&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'Full-Stack Developer',
        experience: '6 years',
        githubLink: 'https://github.com/jameswilson',
        resume: '/public/resumes/james-wilson.pdf',
    },
    {
        firstname: 'Olivia',
        lastname: 'Martinez',
        role: 'candidate',
        phone: '555-1243',
        email: 'olivia.martinez@example.com',
        companyID: 'COMP606',
        password: 'password606',
        profilePic: 'https://images.unsplash.com/photo-1595152772834-219674b2a8a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDI0fHxwcm9maWxlfGVufDB8fHx8MTY4MTQ2NzM3MA&ixlib=rb-1.2.1&q=80&w=400',
        jobRole: 'Graphic Designer',
        experience: '5 years',
        githubLink: 'https://github.com/oliviamartinez',
        resume: '/public/resumes/olivia-martinez.pdf',
    },
    {
        firstname: 'Daniel',
        lastname: 'Anderson',
        role: 'candidate',
        phone: '555-1244',
        email: 'daniel.anderson@example.com',
        companyID: 'COMP707',
        password: 'password707',
        profilePic: 'https://images.unsplash.com/photo-1595152772833-219674b2a8a8?crop=entropy&cs=tinysrgb&fit=max'
    }
]